name: gh-pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: yarn install, deploy
        run: |
          yarn
          yarn deploy